# Using IntelliJ's HTTP client format
### Create User JSON
POST {{host}}/auth/signup
Content-Type: application/json

{"username": "test1@example.com", "password": "Password1!", "password-confirm": "Password1!"}

### Create User
POST {{host}}/auth/signup
Content-Type: application/x-www-form-urlencoded

username=test2@example.com&password=Password1&password-confirm=Password1

### Login
POST {{host}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=test2@example.com&password=Password1

### Add
POST {{host}}/api/v1/ops/add
Content-Type: application/json

{"x": 123, "y": 342}
